# Generated by Django 3.0 on 2020-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0002_auto_20200418_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time', 'booked']},
        ),
        migrations.AddField(
            model_name='availability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
